In [1]:
import numpy as np

In [2]:
cw = [np.array([78., 121., 165.])/255.,
np.array([241., 143., 59.])/255.,
np.array([224., 88., 91.])/255.,
np.array([119., 183., 178.])/255.,
np.array([90., 161., 85.])/255.,
np.array([237., 201., 88.])/255.,
np.array([175., 122., 160.])/255.,
np.array([254., 158., 168.])/255.,
np.array([156., 117., 97.])/255.,
np.array([186., 176., 172.])/255.]

In [3]:
cw

[array([0.30588235, 0.4745098 , 0.64705882]),
 array([0.94509804, 0.56078431, 0.23137255]),
 array([0.87843137, 0.34509804, 0.35686275]),
 array([0.46666667, 0.71764706, 0.69803922]),
 array([0.35294118, 0.63137255, 0.33333333]),
 array([0.92941176, 0.78823529, 0.34509804]),
 array([0.68627451, 0.47843137, 0.62745098]),
 array([0.99607843, 0.61960784, 0.65882353]),
 array([0.61176471, 0.45882353, 0.38039216]),
 array([0.72941176, 0.69019608, 0.6745098 ])]